name: Check tabs in modified files

on:
  push:
     branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - run: echo "The ${{ github.repository }} repository will be cloned to the runner."
      - uses: actions/checkout@v1
      - name: Check new files
        run: echo branch ${GITHUB_REF##*/}

