name: Check tabs in modified files

on:
  push:
     branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [my_runner]
    steps:
      - run: echo "The ${{ github.repository }} repository will be cloned to the runner."
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check tabs in modified files
        run: |
          mkdir Artifacts
          for file in $(git diff --name-only origin/main); do
          (
            echo "Checking file $file" > Artifacts/${file}_artifacts
            awk '{print gsub(/\t/,"")}' $file | awk '{s+=$1} END { print "Count "s }' >> Artifacts/${file}_artifacts  
          ) & 
          done




